name: Tests
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Run example using Puppeteer
        run: npm run example
